language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ahmorsi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ahmorsi/docker-react npm run test