version: '3'

services:
  web:
        build:
          context: .
          dockerfile: Dockerfile.dev
          args:
            - http_proxy=http://ep.threatpulse.net:80
            - https_proxy=http://ep.threatpulse.net:80
        ports:
            - "3000:3000"
        volumes:
          - /app/node_modules
          - .:/app
  tests:
        build:
          context: .
          dockerfile: Dockerfile.dev
          args:
            - http_proxy=http://ep.threatpulse.net:80
            - https_proxy=http://ep.threatpulse.net:80
        volumes:
          - /app/node_modules
          - .:/app
        command: ["npm","run","test"]  